### ISSUE TITLE
Changes for FreePBX 15

### ISSUE THREAD

**Issue by Tetz95** [sorvani/freepbx-helper-scripts#8]
The location of the AMP variables has moved to /etc/asterisk/extensions_additional.conf and a space has been added before and after the equal sign in those variables.

Hope this helps anyone that's upgraded.

**Comment by sorvani** [comment]
The AMP vaiables should not be used int he first place, but were the original exmaples I found when figuring all of this out.

If this is a breaking change with 15, I will look at changing things to use native FreePBX calls as I do in some newer scripts.
